version: '3'

services:
  # project-service:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     - ./SRCS:/SRCS
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    
  # back-service:
  #   build:
  #     context: .
  #     dockerfile: ./devOps/back.Dockerfile
  #   volumes:
  #     - ./back:/back
  #   ports:
  #     - 3000:3000
